# Generated by Django 4.2.10 on 2024-02-29 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя Студента')),
            ],
        ),
        migrations.CreateModel(
            name='StudentProductAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Доступы студентов',
            },
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': 'Урок', 'verbose_name_plural': 'Уроки'},
        ),
        migrations.AlterField(
            model_name='product',
            name='creator',
            field=models.CharField(max_length=100, verbose_name='Автор'),
        ),
        migrations.DeleteModel(
            name='UserProductAccess',
        ),
        migrations.AddField(
            model_name='studentproductaccess',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.AddField(
            model_name='studentproductaccess',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.student'),
        ),
        migrations.AddField(
            model_name='student',
            name='products',
            field=models.ManyToManyField(through='product.StudentProductAccess', to='product.product'),
        ),
        migrations.AlterField(
            model_name='group',
            name='students',
            field=models.ManyToManyField(to='product.student'),
        ),
    ]
